name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract app folder
        run: |
          sudo apt-get update
          sudo apt-get install -y unrar
          # سنحاول فك الضغط بغض النظر عن حالة الأحرف في اسم الملف
          unrar x *.rar  unzip *.zip  true

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew || true

      - name: Build with Gradle
        run: |
          # فحص إذا كان المجلد موجوداً ثم البناء
          ./gradlew assembleDebug --stacktrace
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-snake-game
          path: "**/build/outputs/apk/debug/*.apk"
